### ISSUE TITLE
Constant Sequelize transactions?

### ISSUE THREAD

**Issue by emschwartz** [interledger/five-bells-notary#17]
When running the `five-bells-demo`, the notary seems to be doing a Sequelize transaction every second while sitting idle. Could we replace this behavior with something more like the [`transferExpiryMonitor`](https://github.com/interledger/five-bells-ledger/blob/master/src/lib/transferExpiryMonitor.js) in the ledger?

```shell
...
notary 2016-02-02T23:27:17.759Z sequelize DEBUG Executing (default): SELECT `id`, `case_id`, `notification_target`, `retry_count`, `retry_at`, `created_at`, `updated_at` FROM `Notifications` AS `Notification` WHERE (`Notification`.`retry_at` IS NULL OR `Notification`.`retry_at` < '2016-02-02 23:27:17.758 +00:00');
notary 2016-02-02T23:27:18.767Z sequelize DEBUG Executing (default): SELECT `id`, `case_id`, `notification_target`, `retry_count`, `retry_at`, `created_at`, `updated_at` FROM `Notifications` AS `Notification` WHERE (`Notification`.`retry_at` IS NULL OR `Notification`.`retry_at` < '2016-02-02 23:27:18.764 +00:00');
notary 2016-02-02T23:27:19.774Z sequelize DEBUG Executing (default): SELECT `id`, `case_id`, `notification_target`, `retry_count`, `retry_at`, `created_at`, `updated_at` FROM `Notifications` AS `Notification` WHERE (`Notification`.`retry_at` IS NULL OR `Notification`.`retry_at` < '2016-02-02 23:27:19.772 +00:00');
notary 2016-02-02T23:27:20.778Z sequelize DEBUG Executing (default): SELECT `id`, `case_id`, `notification_target`, `retry_count`, `retry_at`, `created_at`, `updated_at` FROM `Notifications` AS `Notification` WHERE (`Notification`.`retry_at` IS NULL OR `Notification`.`retry_at` < '2016-02-02 23:27:20.777 +00:00');
...
```

**Comment by sentientwaffle** [comment]
The notary behavior is correct; the ledger behavior is not.

When a notification fails its `retry_at` flag is set and it is written back to the database.

In the ledger, the next time notifications are processed (assuming there are no new payments in the mean time), this is run:

```js
if (this._timeout && notifications.length) {
  clearTimeout(this._timeout)
  this._timeout = defer.setTimeout(this.processNotificationQueue.bind(this), this.processingInterval)
}
```

`notifications.length` is `0` because the `retry_at` time hasn't been reached yet, so `processNotificationQueue` is not rescheduled, and the notification will not be retried until another, unrelated transfer is sent, forcing the notification worker to retrieve notifications.

On the other hand, the notary's notification worker schedules `processNotificationQueue` independently of the number of notifications that were fetched, so it doesn't have this issue:
```js
if (notifications.length) {
  this.log.debug('processing ' + notifications.length + ' notifications')
  yield notifications.map(this.processNotification.bind(this))
}
if (this._timeout) { // ← reschedule notification processing no matter what
  clearTimeout(this._timeout)
  this._timeout = defer.setTimeout(this.processNotificationQueue.bind(this), this.processingInterval)
}
```

**Comment by emschwartz** [comment]
Rather than setting the processing interval for 1s the ledger bases its timeout on the earliest date there is actually something it needs to act for: https://github.com/interledger/five-bells-ledger/blob/master/src/lib/timerWorker.js#L39

This is the timeout that schedules `transferExpiryMonitor.processExpiredTransters`: https://github.com/interledger/five-bells-ledger/blob/master/src/lib/timerWorker.js#L50
